# -*- coding: utf-8 -*-
"""proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13k6l60KlxHvXC9znyROFmh1pi-Gc7F-m
"""

# ------------------------------------------------------------
# en esta parte importo todas las librerías necesarias
# ------------------------------------------------------------
import streamlit as st       # streamlit permite crear la página web interactiva
import pandas as pd          # pandas me sirve para manejar la base de datos en excel
import matplotlib.pyplot as plt   # matplotlib me permite crear gráficos dentro de streamlit


# ------------------------------------------------------------
# aquí cargo mi base de datos desde excel
# es importante que el archivo esté en la misma carpeta del proyecto
# y se llame exactamente igual: base_datos_completa_focus.xlsx
# ------------------------------------------------------------
df = pd.read_excel("base_datos_completa_focus.xlsx")

# ------------------------------------------------------------
# creo un menú lateral usando streamlit.sidebar
# este menú permite moverse entre dos páginas:
# - presentación
# - encuesta
# ------------------------------------------------------------

menu = st.sidebar.selectbox("Selecciona una página", ["Presentación", "Encuesta"])

# ============================================================
#                           PÁGINA 1
#                     PRESENTACIÓN DEL PROYECTO
# ============================================================
if menu == "Presentación":

    # título principal centrado
    st.markdown(
        "<h1 style='text-align: center;'>🎧 Study Vibes: Música Para Concentrarte</h1>",
        unsafe_allow_html=True
    )

    # imagen del proyecto
    st.image("musica_estudio.png", use_container_width=True)

    # subtítulo
    st.markdown(
        "<h3 style='text-align: center;'>Una Herramienta Interactiva Para Elegir La Playlist Perfecta Según Tu Estado Emocional</h3>",
        unsafe_allow_html=True
    )

    st.write("")  # espacio estético

    # ----------------------------------------------------------
    #                PRESENTACIÓN DEL PROYECTO
    # ----------------------------------------------------------
    st.markdown(
        "<h2 style='text-align: center;'>Presentación Del Proyecto</h2>",
        unsafe_allow_html=True
    )

    texto_presentacion = """
Hola, soy Yaki. Este proyecto nace de la idea de que la música puede influir directamente en el nivel de 
concentración de una persona. Muchas veces, cuando estudiamos, estamos cansados, estresados, con sueño, 
motivados o incluso ansiosos. A partir de esas emociones, busco música que nos acompañe o nos ayude 
a enfocarnos mejor.

**Study Vibes** es una aplicación que recomienda playlists según dos factores principales:

1. **La emoción actual del usuario**  
2. **La actividad o materia que va a estudiar**

Esta plataforma funciona como una guía rápida para encontrar música adecuada al momento emocional en el que te encuentras. Además, combina datos reales provenientes de un conjunto de playlists de Spotify y YouTube.
"""
    st.markdown(
        f"<div style='text-align: justify; font-size: 18px;'>{texto_presentacion}</div>",
        unsafe_allow_html=True
    )

    # ----------------------------------------------------------
    #                POR QUÉ ELEGÍ ESTE TEMA
    # ----------------------------------------------------------
    st.markdown(
        "<h2 style='text-align: center;'>¿Por Qué Elegí Este Tema?</h2>",
        unsafe_allow_html=True
    )

    texto_motivo = """
Elegí este tema porque la música forma parte de la vida cotidiana de cualquier estudiante.
Muchos de nosotros no podemos estudiar en silencio absoluto, pero tampoco con cualquier género musical.  
La idea de este proyecto es simplificar esa búsqueda y hacerla más personalizada y emocional.
"""
    st.markdown(
        f"<div style='text-align: justify; font-size: 18px;'>{texto_motivo}</div>",
        unsafe_allow_html=True
    )

    # ----------------------------------------------------------
    #                 ESTUDIOS QUE RESPALDAN
    # ----------------------------------------------------------
    st.markdown(
        "<h2 style='text-align: center;'>Estudios Que Respaldan El Proyecto</h2>",
        unsafe_allow_html=True
    )

    texto_estudios = """
Diversos estudios han demostrado que ciertos tipos de música, especialmente el lo-fi, el ambient o el piano suave, 
pueden mejorar el enfoque, la memoria de trabajo y la retención de información.  

Investigaciones en neurociencia indican que la música afecta directamente el sistema límbico, el área del cerebro 
relacionada con las emociones, lo cual influye en nuestro estado mental al estudiar.

Por eso, Study Vibes usa **emociones + actividad académica** para recomendar playlists alineadas a lo que realmente 
necesitas en ese momento.
"""
    st.markdown(
        f"<div style='text-align: justify; font-size: 18px;'>{texto_estudios}</div>",
        unsafe_allow_html=True
    )

    # ----------------------------------------------------------
    #                    GRÁFICO DE DATOS
    # ----------------------------------------------------------
    st.header("Cantidad de playlists por emoción")

    # conteo
    conteo = df["emocion"].value_counts()

    # crear gráfico
    fig, ax = plt.subplots()
    ax.bar(conteo.index, conteo.values)
    ax.set_xlabel("emociones")
    ax.set_ylabel("cantidad")
    ax.set_title("playlists según emoción")
    plt.xticks(rotation=45)

    # mostrar gráfico
    st.pyplot(fig)
# ============================================================
#                           PÁGINA 2
#                     ENCUESTA INTERACTIVA
# ============================================================
elif menu == "Encuesta":

    st.title("Encuesta interactiva 🎵")

    # SELECTBOX EMOCIÓN
    emocion_usuario = st.selectbox(
        "¿cómo te sientes?",
        df["emocion"].unique()
    )

    # SELECTBOX MATERIA
    actividad_usuario = st.selectbox(
        "¿qué vas a estudiar o hacer?",
        df["materia"].unique()
    )

    # SELECTBOX DURACIÓN
    duracion_usuario = st.selectbox(
        "¿qué duración prefieres?",
        df["tipo"].unique()
    )

    # normalizar
    df["emocion"] = df["emocion"].str.lower().str.strip()
    df["materia"] = df["materia"].str.lower().str.strip()
    df["tipo"] = df["tipo"].str.lower().str.strip()

    emocion_usuario = emocion_usuario.lower().strip()
    actividad_usuario = actividad_usuario.lower().strip()
    duracion_usuario = duracion_usuario.lower().strip()

    # filtrado
    resultado = df[
        (df["emocion"] == emocion_usuario) &
        (df["materia"] == actividad_usuario) &
        (df["tipo"] == duracion_usuario)
    ]

    if resultado.empty:
        resultado = df[df["emocion"] == emocion_usuario]

    if resultado.empty:
        resultado = df[df["materia"] == actividad_usuario]

    if resultado.empty:
        resultado = df[df["tipo"] == duracion_usuario]

    if resultado.empty:
        resultado = df.sample(1)

    row = resultado.sample(1).iloc[0]

    st.subheader("🎧 playlist recomendada:")
    st.write("**emocion:**", row["emocion"])
    st.write("**materia:**", row["materia"])
    st.write("**playlist:**", row["playlist"])
    st.write("**duración:**", str(row["duracion"]) + " minutos")
    st.write("**tipo:**", row["tipo"])
    st.write("**año:**", int(row["año"]))
    st.write("**enlace:**", row["link"])